menu:
    博文: /
    归档: /archives/
    工具: /categories/utils/
    开发: /categories/dev/
    生活: /categories/live/
    关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: bubuzou
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2017

