menu:
    home: /
    archives: /archives/
    utils: /categories/utils/
    code: /categories/code/
    knowledge: /categories/knowledge/
    life: /categories/life/
    about: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: bubuzou
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2017

